config/routes.rb
Rails.application.routes.draw do
  get '/home' => 'home#index'
  root 'home#index'
  get "/pages/:page" => "pages#show"
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :user_ids, only: [:new, :create]

  resources :billings, only: [:new, :create] do
    resources :payments, only: [:new, :create]
  end

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  get '/contact' => 'contacts#new', as: :new_contact
  post '/contact' => 'contacts#create', as: :contact

  resources :doctors, only: [:new, :create]
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :payments
  has_many :billings 

  VALID_EMAIL_REGEX = /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: {case_sensitive: false}, format: VALID_EMAIL_REGEX
  validates :first_name, presence: true
  validates :last_name, presence: true
  # validates :avatar, attachment_presence: true

  def name
  "#{first_name}".titleize
  end

  def full_name
    "#{first_name} #{last_name}".squeeze(" ").strip.titleize
  end

  has_attached_file :avatar, styles: { medium: "300x300#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      UserNotifierMailer.send_signup_email(@user).deliver_now 
      redirect_to new_payment_path
    else
      render :new
    end
  end

  def show
    @user = User.find params[:id]
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    @user = User.find params[:id]
    if @user.present?
      @user.update user_params
      @user.update_attribute(:avatar, params[:user][:avatar])
    end
    redirect_to user_path(current_user)
  end

  private

  def user_params
    params.require(:user).permit(:first_name,
                                 :last_name,
                                 :email,
                                 :password,
                                 :password_confirmation,
                                 :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="form-horizontal" style="text-align:center; margin-top:100px;">
  <h1>Account Settings</h1>
  <br>
  <%= form_for @user, html: { multipart: true } do |f| %>
  <div class="form-group">
    <div class="col-sm-4 col-sm-offset-4">
      <%= f.file_field :avatar %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-4 col-sm-offset-4">
      <%= f.text_field :first_name, placeholder: "First name", class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-4 col-sm-offset-4">
      <%= f.text_field :last_name, placeholder: "Last name", class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-4 col-sm-offset-4">
      <%= f.email_field :email, placeholder: "Email", class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-4 col-sm-offset-4">
      <%= f.password_field :password, placeholder: "New password", class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-4 col-sm-offset-4">
      <%= f.password_field :password_confirmation, placeholder: "Confirm password", class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.submit "Update Settings", class: "btn btn-primary", style: "padding: 10px 100px 10px 100px; border-radius: 30px; color: white; background-color:#0094FF; font-family:Helvetica;"%>
  </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<%= render "form" %>

app/views/users/new.html.erb
<nav class="navbar navbar-default navbar-custom navbar-fixed-top" style="background-color: #0094FF;">
    <div class="container-fluid">
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                Menu <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand" href="<%= root_path %>">Merry</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <li>
                <%= link_to "Get Started", new_user_path %>
              </li>
              <li>
                  <%= link_to "About", "/pages/about" %>
              </li>
              <li>
                  <%= link_to "Contact", new_contact_path %>
              </li>
              <% if user_signed_in? %>
                <li><%= link_to "#{current_user.name}", user_path(:id) %><li>
              <% else %>
                <li><%= link_to "Sign In", new_session_path %></li>
              <% end %>
            </ul>
        </div>
    </div>
</nav>
<div class="form-horizontal" style="text-align:center; margin-top:100px;">
  <h1>Create an account to get started!</h1>
  <br>
  <%= @user.errors.full_messages.join(", ") %>
  <%= form_for @user do |f| %>
  <div class="form-group">
    <div class="col-sm-4 col-sm-offset-4">
      <%= f.text_field :first_name, placeholder: "First name", class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-4 col-sm-offset-4">
      <%= f.text_field :last_name, placeholder: "Last name", class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-4 col-sm-offset-4">
      <%= f.email_field :email, placeholder: "Email", class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-4 col-sm-offset-4">
      <%= f.password_field :password, placeholder: "Password", class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-4 col-sm-offset-4">
      <%= f.password_field :password_confirmation, placeholder: "Confirm password", class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.submit "Sign Up", class: "btn btn-primary", style: "padding: 10px 100px 10px 100px; border-radius: 30px; color: white; background-color:#0094FF; font-family:Helvetica;"%>
  </div>
  <% end %>
  <%= link_to "Already have an account?", new_session_path %>
</div>

app/views/users/show.html.erb
<div class="container" style="text-align:center; margin-top:100px;">
  <%= image_tag @user.avatar.url(:medium) %>
  <h1><%= current_user.full_name %></h1>
  <p><%= current_user.email %></p>

  <p><%= link_to "Book Appointment", new_billing_path %></p>

  <p><%= link_to "Edit Account", edit_user_path(current_user) %></p>
</div>