config/routes.rb
Rails.application.routes.draw do
  get '/home' => 'home#index'
  root 'home#index'
  get "/pages/:page" => "pages#show"
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :user_ids, only: [:new, :create]

  resources :billings, only: [:new, :create] do
    resources :payments, only: [:new, :create]
  end

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  get '/contact' => 'contacts#new', as: :new_contact
  post '/contact' => 'contacts#create', as: :contact

  resources :doctors, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/billing.rb
class Billing < ApplicationRecord
  belongs_to :user
  has_many :payments

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :province, presence: true
  validates :postal_code, presence: true  
end

app/models/contact.rb
class Contact < ApplicationRecord

  VALID_EMAIL_REGEX = /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: {case_sensitive: false}, format: VALID_EMAIL_REGEX
  validates :name, presence: true
  validates :message, presence: true 
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_secure_password

  VALID_EMAIL_REGEX = /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: {case_sensitive: false}, format: VALID_EMAIL_REGEX
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :specialty, presence: true
  validates :phone_number, presence: true
end

app/models/payment.rb
class Payment < ApplicationRecord
  require 'active_merchant/billing/rails'

  belongs_to :billing
  after_initialize :init

  attr_accessor :card_security_code
  attr_accessor :credit_card_number
  attr_accessor :expiration_month
  attr_accessor :expiration_year

  # validates :card_security_code, presence: true
  # validates :credit_card_number, presence: true
  # validates :expiration_month, presence: true, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 12 }
  # validates :expiration_year, presence: true
  # validates :amount, presence: true, numericality: { greater_than: 0 }

  # validate :valid_card
  def init
    self.amount ||= 30
  end

  def credit_card
    ActiveMerchant::Billing::CreditCard.new(
      number:              credit_card_number,
      verification_value:  card_security_code,
      month:               expiration_month,
      year:                expiration_year
    )
  end

  # def valid_card
  #   if !credit_card.valid?
  #     errors.add(:base, "The credit card information you provided is not valid. Please double check the information you provided and then try again.")
  #     false
  #   else
  #     true
  #   end
  # end
  #
  # def process
  #   if valid_card
  #     response = GATEWAY.authorize(amount * 100, credit_card)
  #     if response.success?
  #       transaction = GATEWAY.capture(amount * 100, response.authorization)
  #       if !transaction.success?
  #         errors.add(:base, "The credit card you provided was declined.  Please double check your information and try again.") and return
  #         false
  #       end
  #       update_columns({authorization_code: transaction.authorization, success: true})
  #       true
  #     else
  #       errors.add(:base, "The credit card you provided was declined.  Please double check your information and try again.") and return
  #       false
  #     end
  #   end
  # end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :payments
  has_many :billings 

  VALID_EMAIL_REGEX = /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: {case_sensitive: false}, format: VALID_EMAIL_REGEX
  validates :first_name, presence: true
  validates :last_name, presence: true
  # validates :avatar, attachment_presence: true

  def name
  "#{first_name}".titleize
  end

  def full_name
    "#{first_name} #{last_name}".squeeze(" ").strip.titleize
  end

  has_attached_file :avatar, styles: { medium: "300x300#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  layout 'doctor'

  def new
    @doctor = Doctor.new
  end

  def create
    @doctor = Doctor.new doctor_params

  end

  private

  def doctor_params
    params.require(:doctor).permit(:first_name,
                                   :last_name,
                                   :email,
                                   :password,
                                   :password_confirmation,
                                   :phone_number,
                                   :specialty,
                                   :address,
                                   :city,
                                   :province,
                                   :postal_code,
                                   :clinic)

  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end 
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    render template: "pages/#{params[:page]}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      UserNotifierMailer.send_signup_email(@user).deliver_now 
      redirect_to new_payment_path
    else
      render :new
    end
  end

  def show
    @user = User.find params[:id]
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    @user = User.find params[:id]
    if @user.present?
      @user.update user_params
      @user.update_attribute(:avatar, params[:user][:avatar])
    end
    redirect_to user_path(current_user)
  end

  private

  def user_params
    params.require(:user).permit(:first_name,
                                 :last_name,
                                 :email,
                                 :password,
                                 :password_confirmation,
                                 :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/billings_helper.rb
module BillingsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
  def months
  (1..12).collect{|n| ["#{n} - #{Date::MONTHNAMES[n]}", n]}
  end

  def years
    (Time.now.year..Time.now.year+15)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_ids_helper.rb
module UserIdsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Merry</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">

    <title>Merry</title>

    <!-- Bootstrap Core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="css/clean-blog.min.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
  </head>
  <nav class="navbar navbar-default navbar-custom navbar-fixed-top" style="background-color: #0094FF;">
      <div class="container-fluid">
          <div class="navbar-header page-scroll">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  Menu <i class="fa fa-bars"></i>
              </button>
              <a class="navbar-brand" href="<%= root_path %>">Merry</a>
          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav navbar-right">
                <li>
                  <%= link_to "Get Started", new_user_path %>
                </li>
                <li>
                    <%= link_to "About", "/pages/about" %>
                </li>
                <li>
                    <%= link_to "Contact", new_contact_path %>
                </li>
                <% if user_signed_in? %>
                  <li><%= link_to "#{current_user.name}", user_path(current_user) %><li>
                  <li><%= link_to "Sign Out", sessions_path, method: :delete %></li>
                <% else %>
                  <li><%= link_to "Sign In", new_session_path %></li>
                <% end %>
              </ul>
          </div>
      </div>
  </nav>
  <body>
    <%= yield %>
  </body>
<hr>
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <ul class="list-inline text-center">
                    <li>
                        <a href="#">
                            <span class="fa-stack fa-lg">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <span class="fa-stack fa-lg">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <span class="fa-stack fa-lg">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                </ul>
                <p class="copyright text-muted">Copyright &copy; Merry 2016</p>
            </div>
        </div>
    </div>
</footer>
</html>

app/views/layouts/doctor.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Merry</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">

    <title>Merry</title>

    <!-- Bootstrap Core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="css/clean-blog.min.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container" style="text-align:center; margin-top:80px;">
  <h1>About Us</h1>
  <div>
    <%= image_tag "doctor-supply.jpg", class: "about-image" %>
  </div>
  <p>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  </p>
</div>